/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Display;

import java.awt.event.KeyEvent;

/**
 *
 * @author labo10
 */
public class DisplayMenuOption extends javax.swing.JPanel {

    DisplayFrame parent;

    /**
     * Creates new form DisplayMenuMain
     */
    public DisplayMenuOption(DisplayFrame parent) {
        this.parent = parent;
        initComponents();
        this.setSize(994, 445);
        initGroupAndPanel();
        this.setVisible(false);
    }

    public DisplayMenuOption(DisplayFrame parent, int width, int height) {
        this.parent = parent;
        initComponents();
        this.setSize(width, height);
        initGroupAndPanel();
        this.setVisible(false);
    }

    public final void initGroupAndPanel() {
        buttonGroupLevel.add(jRadioButtonSpeedFast);
        buttonGroupLevel.add(jRadioButtonSpeedLow);
        buttonGroupLevel.add(jRadioButtonSpeedNormal);
        buttonGroupSize.add(jRadioButtonSizeBig);
        buttonGroupSize.add(jRadioButtonSizeLittle);
        buttonGroupSize.add(jRadioButtonSizeNormal);
        jRadioButtonSizeBig.setSelected(true);
        jRadioButtonSpeedLow.setSelected(true);
    }

    public void prepareDisplay() {
        switch (parent.getLev()) {
            case 0:
                jRadioButtonSpeedLow.setSelected(true);
                break;
            case 1:
                jRadioButtonSpeedNormal.setSelected(true);
                break;
            case 2:
                jRadioButtonSpeedFast.setSelected(true);
                break;
        }
        switch (parent.getSiz()) {
            case 0:
                jRadioButtonSizeBig.setSelected(true);
                break;
            case 1:
                jRadioButtonSizeNormal.setSelected(true);
                break;
            case 2:
                jRadioButtonSizeLittle.setSelected(true);
                break;
        }
        this.jTextFieldPort.setText("" + parent.getPortLan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLevel = new javax.swing.ButtonGroup();
        buttonGroupSize = new javax.swing.ButtonGroup();
        jButtonExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelSpeed = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonSpeedFast = new javax.swing.JRadioButton();
        jRadioButtonSpeedLow = new javax.swing.JRadioButton();
        jRadioButtonSpeedNormal = new javax.swing.JRadioButton();
        jPanelSize = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonSizeLittle = new javax.swing.JRadioButton();
        jRadioButtonSizeBig = new javax.swing.JRadioButton();
        jRadioButtonSizeNormal = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        jButtonExit.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 0, 0));
        jButtonExit.setText("Return");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        add(jButtonExit);
        jButtonExit.setBounds(240, 320, 510, 60);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("- BoolGame -");
        add(jLabel1);
        jLabel1.setBounds(190, 20, 610, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Options");
        add(jLabel2);
        jLabel2.setBounds(190, 60, 610, 30);

        jPanelSpeed.setBackground(new java.awt.Color(0, 0, 0));
        jPanelSpeed.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        jPanelSpeed.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select speed level :");
        jLabel3.setToolTipText("");
        jPanelSpeed.add(jLabel3);
        jLabel3.setBounds(10, 10, 220, 17);

        jRadioButtonSpeedFast.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonSpeedFast.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonSpeedFast.setText("Fast");
        jRadioButtonSpeedFast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSpeedFastActionPerformed(evt);
            }
        });
        jPanelSpeed.add(jRadioButtonSpeedFast);
        jRadioButtonSpeedFast.setBounds(90, 100, 70, 23);

        jRadioButtonSpeedLow.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonSpeedLow.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonSpeedLow.setText("Low");
        jRadioButtonSpeedLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSpeedLowActionPerformed(evt);
            }
        });
        jPanelSpeed.add(jRadioButtonSpeedLow);
        jRadioButtonSpeedLow.setBounds(90, 40, 70, 23);

        jRadioButtonSpeedNormal.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonSpeedNormal.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonSpeedNormal.setText("Normal");
        jRadioButtonSpeedNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSpeedNormalActionPerformed(evt);
            }
        });
        jPanelSpeed.add(jRadioButtonSpeedNormal);
        jRadioButtonSpeedNormal.setBounds(90, 70, 70, 23);

        add(jPanelSpeed);
        jPanelSpeed.setBounds(240, 110, 240, 140);

        jPanelSize.setBackground(new java.awt.Color(0, 0, 0));
        jPanelSize.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        jPanelSize.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Select bar size :");
        jPanelSize.add(jLabel4);
        jLabel4.setBounds(10, 10, 220, 17);

        jRadioButtonSizeLittle.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonSizeLittle.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonSizeLittle.setText("Little");
        jRadioButtonSizeLittle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSizeLittleActionPerformed(evt);
            }
        });
        jPanelSize.add(jRadioButtonSizeLittle);
        jRadioButtonSizeLittle.setBounds(90, 100, 80, 23);

        jRadioButtonSizeBig.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonSizeBig.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonSizeBig.setText("Big");
        jRadioButtonSizeBig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSizeBigActionPerformed(evt);
            }
        });
        jPanelSize.add(jRadioButtonSizeBig);
        jRadioButtonSizeBig.setBounds(90, 40, 70, 23);

        jRadioButtonSizeNormal.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonSizeNormal.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonSizeNormal.setText("Normal");
        jRadioButtonSizeNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSizeNormalActionPerformed(evt);
            }
        });
        jPanelSize.add(jRadioButtonSizeNormal);
        jRadioButtonSizeNormal.setBounds(90, 70, 70, 23);

        add(jPanelSize);
        jPanelSize.setBounds(510, 110, 240, 140);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Port for Lan party : (enter to valid)");
        jLabel5.setToolTipText("");
        add(jLabel5);
        jLabel5.setBounds(240, 270, 240, 30);

        jTextFieldPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPortKeyReleased(evt);
            }
        });
        add(jTextFieldPort);
        jTextFieldPort.setBounds(510, 270, 240, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        parent.ChangePanel(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jRadioButtonSpeedLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSpeedLowActionPerformed
        parent.setLevel(0);
    }//GEN-LAST:event_jRadioButtonSpeedLowActionPerformed

    private void jRadioButtonSizeBigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSizeBigActionPerformed
        parent.setSize(0);
    }//GEN-LAST:event_jRadioButtonSizeBigActionPerformed

    private void jRadioButtonSpeedNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSpeedNormalActionPerformed
        parent.setLevel(1);
    }//GEN-LAST:event_jRadioButtonSpeedNormalActionPerformed

    private void jRadioButtonSpeedFastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSpeedFastActionPerformed
        parent.setLevel(2);
    }//GEN-LAST:event_jRadioButtonSpeedFastActionPerformed

    private void jRadioButtonSizeNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSizeNormalActionPerformed
        parent.setSize(1);
    }//GEN-LAST:event_jRadioButtonSizeNormalActionPerformed

    private void jRadioButtonSizeLittleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSizeLittleActionPerformed
        parent.setSize(2);
    }//GEN-LAST:event_jRadioButtonSizeLittleActionPerformed

    private void jTextFieldPortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPortKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                parent.setPortLan(Integer.parseInt(jTextFieldPort.getText()));
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_jTextFieldPortKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupLevel;
    private javax.swing.ButtonGroup buttonGroupSize;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelSize;
    private javax.swing.JPanel jPanelSpeed;
    private javax.swing.JRadioButton jRadioButtonSizeBig;
    private javax.swing.JRadioButton jRadioButtonSizeLittle;
    private javax.swing.JRadioButton jRadioButtonSizeNormal;
    private javax.swing.JRadioButton jRadioButtonSpeedFast;
    private javax.swing.JRadioButton jRadioButtonSpeedLow;
    private javax.swing.JRadioButton jRadioButtonSpeedNormal;
    private javax.swing.JTextField jTextFieldPort;
    // End of variables declaration//GEN-END:variables
}
