/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Display;

/**
 *
 * @author labo10
 */
public class DisplayMenuMain extends javax.swing.JPanel {
    DisplayFrame parent;

    /**
     * Creates new form DisplayMenuMain
     */
    public DisplayMenuMain(DisplayFrame parent) {
        this.parent = parent;
        initComponents();
        this.setSize(994, 445);
        this.setVisible(false);
    }

    public DisplayMenuMain(DisplayFrame parent,int width, int height) {
        this.parent = parent;
        initComponents();
        this.setSize(width, height);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNew = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonOption = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        jButtonNew.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jButtonNew.setForeground(new java.awt.Color(255, 0, 0));
        jButtonNew.setText("New Game !");
        jButtonNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonNewMouseReleased(evt);
            }
        });
        add(jButtonNew);
        jButtonNew.setBounds(240, 120, 510, 60);

        jButtonExit.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 0, 0));
        jButtonExit.setText("Exit !");
        jButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonExitMouseReleased(evt);
            }
        });
        add(jButtonExit);
        jButtonExit.setBounds(240, 320, 510, 60);

        jButtonOption.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jButtonOption.setForeground(new java.awt.Color(255, 0, 0));
        jButtonOption.setText("Options !");
        jButtonOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonOptionMouseReleased(evt);
            }
        });
        add(jButtonOption);
        jButtonOption.setBounds(240, 220, 510, 60);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("- BoolGame -");
        add(jLabel2);
        jLabel2.setBounds(190, 20, 610, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNewMouseReleased
        parent.ChangePanel(1);
    }//GEN-LAST:event_jButtonNewMouseReleased

    private void jButtonOptionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOptionMouseReleased
        parent.ChangePanel(2);
    }//GEN-LAST:event_jButtonOptionMouseReleased

    private void jButtonExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMouseReleased
        System.exit(0);
    }//GEN-LAST:event_jButtonExitMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonOption;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
