/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Display;

/**
 *
 * @author labo10
 */
public class DisplayBar extends javax.swing.JPanel {

    DisplayFrame parent;

    /**
     * Creates new form DisplayBar
     */
    public DisplayBar(DisplayFrame parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonLaunch = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(994, 30));
        setMinimumSize(new java.awt.Dimension(994, 30));
        setPreferredSize(new java.awt.Dimension(994, 30));
        setLayout(null);

        jButton1.setText("Home");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(0, 0, 90, 30);

        jButton2.setText("Exit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(110, 0, 90, 30);

        jButtonLaunch.setText("Launch");
        jButtonLaunch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonLaunchMouseReleased(evt);
            }
        });
        add(jButtonLaunch);
        jButtonLaunch.setBounds(220, 0, 90, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        if (parent.getOldPanel() == 11) {
            parent.StopGame();
        }
        parent.ChangePanel(0);
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButtonLaunchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLaunchMouseReleased
        if (parent.getOldPanel() == 11) {
            if (parent.getServer() == 0) {
                parent.LaunchLocalGame();
            }
        }
    }//GEN-LAST:event_jButtonLaunchMouseReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonLaunch;
    // End of variables declaration//GEN-END:variables
}
