/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Display;

/**
 *
 * @author labo10
 */
public class DisplayMenuNewGameLanJoin extends javax.swing.JPanel {
    DisplayFrame parent;
    /**
     * Creates new form DisplayMenuMain
     */
    public DisplayMenuNewGameLanJoin(DisplayFrame parent) {
        this.parent = parent;
        initComponents();
        this.setSize(994, 445);
        this.setVisible(false);
    }

    public DisplayMenuNewGameLanJoin(DisplayFrame parent,int width, int height) {
        this.parent = parent;
        initComponents();
        this.setSize(width, height);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonJoin = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        jButtonJoin.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jButtonJoin.setForeground(new java.awt.Color(255, 0, 0));
        jButtonJoin.setText("Join");
        jButtonJoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonJoinMouseReleased(evt);
            }
        });
        add(jButtonJoin);
        jButtonJoin.setBounds(240, 220, 510, 60);

        jButtonExit.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 0, 0));
        jButtonExit.setText("Return");
        jButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonExitMouseReleased(evt);
            }
        });
        add(jButtonExit);
        jButtonExit.setBounds(240, 320, 510, 60);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("- BoolGame -");
        add(jLabel1);
        jLabel1.setBounds(190, 20, 610, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Join party");
        add(jLabel2);
        jLabel2.setBounds(190, 60, 610, 30);

        jTextFieldIp.setText("127.0.0.1");
        add(jTextFieldIp);
        jTextFieldIp.setBounds(340, 140, 410, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("IP :");
        add(jLabel3);
        jLabel3.setBounds(240, 140, 80, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJoinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJoinMouseReleased
        parent.LaunchServerGame(false, this.jTextFieldIp.getText());
    }//GEN-LAST:event_jButtonJoinMouseReleased

    private void jButtonExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMouseReleased
        parent.ChangePanel(12);
    }//GEN-LAST:event_jButtonExitMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonJoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldIp;
    // End of variables declaration//GEN-END:variables
}
